apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.app }}
    tier: {{ .Values.tier }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
      tier: {{ .Values.tier }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        tier: {{ .Values.tier }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        name: {{ .Values.name }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: fc-mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: fitcycle-persistent-storage
        - mountPath: /docker-entrypoint-initdb.d
          name: mysql-initdb
        - mountPath: /etc/mysql/conf.d
          name: mysql-cnf-config
      - image: "{{ .Values.telegraf.image.repository }}:{{ .Values.telegraf.image.tag }}"
        name: telegraf
        ports:
        - name: udp-statsd
          containerPort: 8125
        - name: udp-8092
          containerPort: 8092
        - name: tcp-8094
          containerPort: 8094
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WAVEFRONT_PROXY
          value: wavefront-proxy
        - name: INTERVAL
          value: 60s
        - name: METRIC_SOURCE_NAME
          # This can be change to use the Deployment / Statefulset name instead as a simple value
          # The metric source name should not be an ephemeral value
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: telegraf-mysql-config
          mountPath: /etc/telegraf/telegraf.d
      volumes:
      - name: fitcycle-persistent-storage
        persistentVolumeClaim:
          claimName: fc-mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
      - name: telegraf-mysql-config
        configMap:
          name: telegraf-mysql-config
      - name: mysql-cnf-config
        configMap:
          name: mysql-cnf-config

