apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  labels:
    app: {{ .Values.app }}
    tier: {{ .Values.tier }}
    chart: {{ template "mysql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 3306
      name: http-fc-db
  selector:
    app: {{ .Values.app }}
    tier: {{ .Values.tier }}
    release: {{ .Release.Name }}
  clusterIP: None
