apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes that installs the wavefront-proxy
name: wavefront-proxy
version: 0.1.0
maintainers:
  - name: Bill Shetti
    email: billshetti@gmail.com

