apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiserver.service.name }}
  labels:
    app: {{ .Values.app }}
    tier: {{ .Values.tier }}
    chart: {{ template "api-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: http-fc
      protocol: TCP
      port: 5000
      nodePort: 30431
  selector:
    app: {{ .Values.app }}
    tier: {{ .Values.tier }}
    release: {{ .Release.Name }}
  type: {{ .Values.apiserver.service.type }}
