apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webserver.service.name }} 
  labels:
    app: {{ .Values.app }}
    tier: {{ .Values.tier }}
    chart: {{ template "web-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      name: http-fcweb
      nodePort: 30440
      protocol: TCP
  selector:
    app: {{ .Values.app }}
    tier: {{ .Values.tier }}
    release: {{ .Release.Name }}
  type: {{ .Values.webserver.service.type }}
