apiVersion: apps/v1beta2
kind: Deployment
#apiVersion: v1 # for versions before 1.8.0 use apps/v1beta1
#kind: ReplicationController
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.app }}
    name: {{ .Values.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }} 
        release: {{ .Release.Name }} 
    spec:
      containers:
      - name: {{ .Values.name }} 
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: WAVEFRONT_URL
          value: {{ .Values.wavefrontUrl }} 
        - name: WAVEFRONT_TOKEN
          value: {{ .Values.wavefrontToken }} 
        ports:
        - containerPort: 2878
          protocol: TCP
        - containerPort: 4242
          protocol: TCP
        securityContext:
          privileged: false

