apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name  }}
  labels:
    app: {{ .Values.app }}
    chart: {{ template "wavefront-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: wavefront
    port: 2878
    protocol: TCP
  - name: opentsdb
    port: 4242
    protocol: TCP
  selector:
    app: {{ .Values.app }}
    release: {{ .Release.Name }}

